### ISSUE TITLE
Consider renaming the project

### ISSUE THREAD

**Issue by GiedriusS** [sherifabdlnaby/rubban#2]
Hello! First of all, thanks for the project! We have considered making something similar at $MY_CURRENT_COMPANY. However, there is another popular project with the same name at https://bosun.org/. Please consider renaming this to something else so that it wouldn't clash :P

**Comment by sherifabdlnaby** [comment]
Unfortunately, I figured that out late. however, since It's still early stages of the project a rename won't be a problem. I'll do it as soon as I get back to work. Thank you!


Keeping the issue open until then 👍

**Comment by sherifabdlnaby** [comment]
Renamed project to `Ruban` which is a close Arabic translation to Bosun 😄
